name: Application CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'functions/**'
      - 'Makefile'
      - 'pyproject.toml'
      - 'poetry.lock'
      - '.github/workflows/application-ci.yml'
      - 'docs/architecture.py' # Trigger on diagram code changes

jobs:
  test-and-lint:
    name: Test and Lint Python Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python & Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: make install
      - name: Run linting checks
        run: make lint
      - name: Run unit tests
        run: make test

# --- Architecture Diagram JOB ---
  generate-diagram:
    name: Generate Architecture Diagram
    needs: test-and-lint # Run after tests pass
    runs-on: ubuntu-latest

    steps:
      # This step now explicitly checks out the PR branch
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python & Poetry
        uses: snok/install-poetry@v1

      - name: Install Graphviz
        run: sudo apt-get update && sudo apt-get install -y graphviz

      - name: Install Python Dependencies
        run: make install

      - name: Generate Diagram
        run: poetry run python docs/architecture.py

      # This step now pushes back to the correct branch
      - name: Commit diagram changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs/architecture.png
          # Use || true to prevent the step from failing if there's nothing to commit.
          git diff --staged --quiet || (git commit -m "docs(bot): auto-generate architecture diagram" && git push)